class E:
    BOOT=              "BOOT"
    SWITCH_UP=         "SWITCH_UP"
    SWITCH_DOWN=       "SWITCH_DOWN"
    PACKET_IN=         "PACKET_IN"
    FLOW_ADD=          "FLOW_ADD"
    GOSSIP_RECV=       "GOSSIP_RECV"
    CONSENSUS_OK=      "CONSENSUS_OK"
    HASH_MISMATCH=     "HASH_MISMATCH"
    SIG_INVALID=       "SIG_INVALID"
    FLOW_INJECT=       "FLOW_INJECT"
    REPLAY=            "REPLAY"
    FLOOD=             "FLOOD"
    CTRL_OFFLINE=      "CTRL_OFFLINE"
    FAKE_CTRL=         "FAKE_CTRL"
    UNAUTH_SW=         "UNAUTH_SW"
    CONSENSUS_FAIL=    "CONSENSUS_FAIL"
    AUDIT_START=       "AUDIT_START"

ATTACK_TYPES = {
    E.HASH_MISMATCH, E.SIG_INVALID, E.FLOW_INJECT,
    E.REPLAY, E.FLOOD, E.CTRL_OFFLINE, E.FAKE_CTRL,
    E.UNAUTH_SW, E.CONSENSUS_FAIL,
}
